defaults:
  - _self_
  - model: XLinear
  - data: Wiki10-31k

tasks: ["eval"]


eval:
  metrics: ["ndcg","precision"]
  thresholds: [1,5,10]
  label_cls: ["tail", "head"]

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

prediction:
  dir: resource/prediction/

ranking:
  dir: resource/ranking/

result:
  dir: resource/result/








